// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: validate/expression.proto

package validate

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on Constraint with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Constraint) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Constraint with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ConstraintMultiError, or
// nil if none found.
func (m *Constraint) ValidateAll() error {
	return m.validate(true)
}

func (m *Constraint) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Message

	// no validation rules for Expression

	if len(errors) > 0 {
		return ConstraintMultiError(errors)
	}

	return nil
}

// ConstraintMultiError is an error wrapping multiple validation errors
// returned by Constraint.ValidateAll() if the designated constraints aren't met.
type ConstraintMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ConstraintMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ConstraintMultiError) AllErrors() []error { return m }

// ConstraintValidationError is the validation error returned by
// Constraint.Validate if the designated constraints aren't met.
type ConstraintValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ConstraintValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ConstraintValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ConstraintValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ConstraintValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ConstraintValidationError) ErrorName() string { return "ConstraintValidationError" }

// Error satisfies the builtin error interface
func (e ConstraintValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sConstraint.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ConstraintValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ConstraintValidationError{}

// Validate checks the field values on Violations with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Violations) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Violations with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ViolationsMultiError, or
// nil if none found.
func (m *Violations) ValidateAll() error {
	return m.validate(true)
}

func (m *Violations) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	for idx, item := range m.GetViolations() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, ViolationsValidationError{
						field:  fmt.Sprintf("Violations[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, ViolationsValidationError{
						field:  fmt.Sprintf("Violations[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return ViolationsValidationError{
					field:  fmt.Sprintf("Violations[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return ViolationsMultiError(errors)
	}

	return nil
}

// ViolationsMultiError is an error wrapping multiple validation errors
// returned by Violations.ValidateAll() if the designated constraints aren't met.
type ViolationsMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ViolationsMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ViolationsMultiError) AllErrors() []error { return m }

// ViolationsValidationError is the validation error returned by
// Violations.Validate if the designated constraints aren't met.
type ViolationsValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ViolationsValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ViolationsValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ViolationsValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ViolationsValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ViolationsValidationError) ErrorName() string { return "ViolationsValidationError" }

// Error satisfies the builtin error interface
func (e ViolationsValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sViolations.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ViolationsValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ViolationsValidationError{}

// Validate checks the field values on Violation with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Violation) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Violation with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ViolationMultiError, or nil
// if none found.
func (m *Violation) ValidateAll() error {
	return m.validate(true)
}

func (m *Violation) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for FieldPath

	// no validation rules for ConstraintId

	// no validation rules for Message

	// no validation rules for ForKey

	if len(errors) > 0 {
		return ViolationMultiError(errors)
	}

	return nil
}

// ViolationMultiError is an error wrapping multiple validation errors returned
// by Violation.ValidateAll() if the designated constraints aren't met.
type ViolationMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ViolationMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ViolationMultiError) AllErrors() []error { return m }

// ViolationValidationError is the validation error returned by
// Violation.Validate if the designated constraints aren't met.
type ViolationValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ViolationValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ViolationValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ViolationValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ViolationValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ViolationValidationError) ErrorName() string { return "ViolationValidationError" }

// Error satisfies the builtin error interface
func (e ViolationValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sViolation.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ViolationValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ViolationValidationError{}
